Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provision "shell" do |s|
    s.privileged = true
    s.inline = "if [ ! -e /root/.ssh ]; then mkdir -p /root/.ssh; fi; echo #{ENV['PUBLICKEY']} >> /root/.ssh/authorized_keys;"
  end

end
